language: java

dist: trusty

jobs:
  include:
    - name: OpenJDK 8
      jdk: openjdk8
    - name: OracleJDK 8
      jdk: oraclejdk8
    - name: OpenJDK 11
      jdk: openjdk11
    - name: OracleJDK 11
      jdk: oraclejdk11

cache:
  directories:
    - $HOME/.m2

before_script:
  - pip install --user codecov

script:
  - mvn clean verify -B -U

after_success:
  - bash <(curl -s https://codecov.io/bash)